# Generated by Django 4.2.6 on 2023-10-28 20:17

import django.core.validators
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='ratings',
            field=models.IntegerField(default=0, verbose_name='Ratings'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to=pathlib.PureWindowsPath('C:/Users/AndreaHrelja/Public/django-videos/media'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'png'])]),
        ),
    ]
