# Generated by Django 4.2.6 on 2023-10-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_ratings_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category_type',
            field=models.CharField(choices=[('ELEMENTARY', 'Elementary School'), ('HIGH', 'High School')], default='ELEMENTARY', max_length=12, verbose_name='Scholar Seniority'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
