# Generated by Django 4.2.6 on 2023-10-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_category_type_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category_subtype',
            field=models.CharField(choices=[('1', '1st year'), ('2', '2nd year'), ('3', '3rd year'), ('4', '4th year'), ('5', '5th year'), ('6', '6th year'), ('7', '7th year'), ('8', '8th year')], default='1', max_length=1, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category_type',
            field=models.CharField(choices=[('ELEMENTARY', 'Elementary School'), ('HIGH', 'High School')], default='HIGH', max_length=12, verbose_name='Scholar Seniority'),
        ),
    ]
